export const SIDEBAR_TOGGLE = 'SIDEBAR_TOGGLE';

export const TABLE_FIRST_DRAG_AND_DROP = 'TABLE_FIRST_DRAG_AND_DROP';
export const TABLE_FIRST_PIN = 'TABLE_FIRST_PIN';

export const TABLE_SECOND_DRAG_AND_DROP = 'TABLE_SECOND_DRAG_AND_DROP';
export const TABLE_SECOND_PIN = 'TABLE_SECOND_PIN';

export const TABLE_THIRD_DRAG_AND_DROP = 'TABLE_THIRD_DRAG_AND_DROP';
export const TABLE_THIRD_PIN = 'TABLE_THIRD_PIN';

export const TABLE_FOURTH_DRAG_AND_DROP = 'TABLE_FOURTH_DRAG_AND_DROP';
export const TABLE_FOURTH_PIN = 'TABLE_FOURTH_PIN';